### Creates a new employee entity
POST http://localhost:4000/employees
Content-Type: application/json

{
  "name": "Doenjj John",
  "email": "ohaa@example.com",
  "address": "2 street north",
  "dateOfBirth": "2001-11-12",
  "registeredDate": "2023-05-10"
}
###